drop table if exists quiz;

create table quiz
(
    id         bigint generated by default as identity,
    title      varchar(255),
    desc       varchar(255),
    timer      bigint,
    answer     bigint,
    select1    varchar(255),
    select2    varchar(255),
    select3    varchar(255),
    select4    varchar(255),
    open_at    date,
    open_time  time,
    end_time   time,
    created_at timestamp,
    updated_at timestamp,
    primary key (id)
);